"""
EncroWatch v2 — PDF Report Generator
Water Body Encroachment Detection Report
"""

import io
import logging
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT

logger = logging.getLogger(__name__)


def generate_water_report(analysis: dict, meta: dict, user: dict) -> bytes:
    """
    Generate a PDF report for water body encroachment analysis.
    
    Args:
        analysis: Analysis results dictionary
        meta: Metadata (water body name, date range, etc.)
        user: User info (name, role)
    
    Returns:
        PDF as bytes
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#1a5276'),
        spaceAfter=20,
        alignment=TA_CENTER
    )
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=12,
        textColor=colors.HexColor('#2874a6'),
        spaceAfter=10,
        spaceBefore=15
    )
    normal_style = styles['Normal']
    
    # Build story
    story = []
    
    # Title
    story.append(Paragraph("EncroWatch v2", title_style))
    story.append(Paragraph("Water Body Encroachment Detection Report", title_style))
    story.append(Spacer(1, 20))
    
    # Report Info
    story.append(Paragraph("Report Information", heading_style))
    report_data = [
        ['Report Date:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
        ['Generated By:', user.get('name', 'Unknown')],
        ['Role:', user.get('role', 'Inspector')],
        ['Water Body:', meta.get('water_body', 'N/A')],
        ['Analysis Period:', meta.get('date_range', 'N/A')],
    ]
    t = Table(report_data, colWidths=[2*inch, 3.5*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e8f4f8')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
    ]))
    story.append(t)
    story.append(Spacer(1, 20))
    
    # Analysis Summary
    story.append(Paragraph("Analysis Summary", heading_style))
    
    if analysis:
        # Key metrics
        metrics = []
        if 'total_area_ha' in analysis:
            metrics.append(['Total Water Body Area', f"{analysis['total_area_ha']:.2f} ha"])
        if 'encroached_area_ha' in analysis:
            metrics.append(['Encroached Area', f"{analysis['encroached_area_ha']:.2f} ha"])
        if 'encroachment_pct' in analysis:
            metrics.append(['Encroachment Percentage', f"{analysis['encroachment_pct']:.1f}%"])
        if 'change_detected' in analysis:
            status = "Yes" if analysis['change_detected'] else "No"
            metrics.append(['Change Detected', status])
        
        if metrics:
            t = Table(metrics, colWidths=[2.5*inch, 2*inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#fef9e7')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('PADDING', (0, 0), (-1, -1), 8),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ]))
            story.append(t)
        
        # Encroachment Details
        if 'encroachment_details' in analysis:
            story.append(Spacer(1, 15))
            story.append(Paragraph("Encroachment Details", heading_style))
            details = analysis['encroachment_details']
            if isinstance(details, list):
                for i, detail in enumerate(details[:10], 1):  # Limit to 10
                    story.append(Paragraph(f"{i}. {detail}", normal_style))
            elif isinstance(details, dict):
                for k, v in details.items():
                    story.append(Paragraph(f"<b>{k}:</b> {v}", normal_style))
        
        # Recommendations
        if 'recommendations' in analysis:
            story.append(Spacer(1, 15))
            story.append(Paragraph("Recommendations", heading_style))
            recs = analysis['recommendations']
            if isinstance(recs, list):
                for rec in recs:
                    story.append(Paragraph(f"• {rec}", normal_style))
            else:
                story.append(Paragraph(str(recs), normal_style))
    else:
        story.append(Paragraph("No analysis data available.", normal_style))
    
    # Footer
    story.append(Spacer(1, 30))
    story.append(Paragraph(
        "— This is an automated report generated by EncroWatch v2 —",
        ParagraphStyle('Footer', parent=normal_style, fontSize=9, textColor=colors.grey, alignment=TA_CENTER)
    ))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()